import { ResultSetHeader, RowDataPacket } from "mysql2";
import { db } from "../Shared/database/connections.js";
import { Repository } from "../Shared/repository.js";
import { AudiovisualType, Review } from "./review.entity.js";

/** Shape of a row returned by MySQL from the reviews table. */
type ReviewRow = RowDataPacket & {
    id: number;
    viewer_id: number;
    rating: number | boolean;
    audiovisual_id: number;
    audiovisual_type: AudiovisualType;
};

/** Converts SQL column names and values into the application model. */
const toReview = (row: ReviewRow) => new Review(
    Number(row.viewer_id), Boolean(row.rating), Number(row.audiovisual_id), row.audiovisual_type, Number(row.id),
);

export class ReviewRepository implements Repository<Review> {
    /** Returns all reviews ordered by their ID. */
    async findAll(): Promise<Review[]> {
        const [rows] = await db.query<ReviewRow[]>("SELECT id, viewer_id, rating, audiovisual_id, audiovisual_type FROM reviews ORDER BY id");
        return rows.map(toReview);
    }

    /** Finds a review by its primary key. */
    async findOne(id: number): Promise<Review | undefined> {
        const [rows] = await db.query<ReviewRow[]>("SELECT id, viewer_id, rating, audiovisual_id, audiovisual_type FROM reviews WHERE id = ?", [id]);
        return rows[0] ? toReview(rows[0]) : undefined;
    }

    /** Lists ratings linked to a specific movie or episode. */
    async findByAudiovisual(type: AudiovisualType, audiovisualId: number): Promise<Review[]> {
        const [rows] = await db.query<ReviewRow[]>(
            "SELECT id, viewer_id, rating, audiovisual_id, audiovisual_type FROM reviews WHERE audiovisual_type = ? AND audiovisual_id = ? ORDER BY id",
            [type, audiovisualId],
        );
        return rows.map(toReview);
    }

    /** Lists all ratings submitted by a viewer. */
    async findByViewer(viewerId: number): Promise<Review[]> {
        const [rows] = await db.query<ReviewRow[]>("SELECT id, viewer_id, rating, audiovisual_id, audiovisual_type FROM reviews WHERE viewer_id = ? ORDER BY id", [viewerId]);
        return rows.map(toReview);
    }

    /** Saves a review and assigns the ID generated by MySQL. */
    async create(item: Review): Promise<Review> {
        const [result] = await db.execute<ResultSetHeader>(
            "INSERT INTO reviews (viewer_id, rating, audiovisual_id, audiovisual_type) VALUES (?, ?, ?, ?)",
            [item.viewerId, item.rating, item.audiovisualId, item.audiovisualType],
        );
        item.id = result.insertId;
        return item;
    }

    /** Updates only the properties supplied in the request. */
    async update(id: number, input: Partial<Review>): Promise<Review | undefined> {
        const allowed = ["viewerId", "rating", "audiovisualId", "audiovisualType"] as const;
        const columns = { viewerId: "viewer_id", rating: "rating", audiovisualId: "audiovisual_id", audiovisualType: "audiovisual_type" };
        const fields = allowed.filter((field) => input[field] !== undefined);
        if (!fields.length) return this.findOne(id);
        const values = fields.map((field) => input[field]) as Array<string | number | boolean>;
        await db.execute(`UPDATE reviews SET ${fields.map((field) => `${columns[field]} = ?`).join(", ")} WHERE id = ?`, [...values, id]);
        return this.findOne(id);
    }

    /** Deletes the requested review and reports whether it existed. */
    async delete(id: number): Promise<boolean> {
        const [result] = await db.execute<ResultSetHeader>("DELETE FROM reviews WHERE id = ?", [id]);
        return result.affectedRows > 0;
    }
}
