GET http://localhost:3000/api/movie

###
GET http://localhost:3000/api/movie

###
POST http://localhost:3000/api/movie
Content-Type: application/json

{
  "id_author": 2,
  "path": "asd",
  "tittle": "Back to the Future",
  "category": "fiction",
  "views": 0,
  "description": "very good",
  "state": true
}

###
PUT http://localhost:3000/api/movie/2
Content-Type: application/json

{
  "description": "regular"
}

###
DELETE  http://localhost:3000/api/movie/1
Content-Type: application/json